name: 子域注册申请
description: 在这里提交申请, 以注册 xxx.fucksc.cf 子域(注册 456789 级子域/变更请在原 issue 发表评论并 @zhegeshijieshangzuishuaideren)
title: "子域注册申请 [xxx]"
labels: 子域注册申请
assignees:
  - zhegeshijieshangzuishuaideren
body:
  - type: dropdown
    id: type
    attributes:
      label: 类型
      multiple: false
      options:
        - A
        - AAAA
        - CNAME
        - TXT
        - 跳转至自定义 url
    validations:
      required: true
  - type: input
    id: value
    attributes:
      label: 值
      description: IP 地址/CNAME 域名/TXT 记录值/自定义 url
      placeholder: e.g. 123.132.231/baidu.com/I f*** CCF/https://example.com
    validations:
      required: true
  - type: checkboxes
    id: cloudflare
    attributes:
      label: 套 Cloudflare 代理加速访问
      description: 如果你的网站访问速度足够快, 不建议勾选; 跳转至自定义 url 不支持该选项
      options:
        - label: 为我的网站套 Cloudflare 代理
          required: false
  - type: input
    id: invite
    attributes:
      label: 邀请信息
      description: (选填)哪位 GitHub 用户邀请您注册 xxx.fucksc.cf 子域
      placeholder: GitHub 用户名
    validations:
      required: false
  - type: textarea
    id: notice
    attributes:
      label: 其他说明
    validations:
      required: false
